// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-w3yX0XumcKfEh_VqWb-Vyty_HDEoBo',
    appId: '1:521038574400:web:30e63868ab0f72333000a5',
    messagingSenderId: '521038574400',
    projectId: 'dazzling-app',
    authDomain: 'dazzling-app.firebaseapp.com',
    storageBucket: 'dazzling-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyAEXjkqXsOwTlCxRWDtbxOmM7U5YX_Hc',
    appId: '1:521038574400:android:e34d20f1dc13897b3000a5',
    messagingSenderId: '521038574400',
    projectId: 'dazzling-app',
    storageBucket: 'dazzling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhV08Cig6OK2RFmADSN7PvKIM1leE7xU',
    appId: '1:521038574400:ios:6ea7b0a9a30035123000a5',
    messagingSenderId: '521038574400',
    projectId: 'dazzling-app',
    storageBucket: 'dazzling-app.firebasestorage.app',
    iosBundleId: 'com.example.dazzling',
  );
}
